import { config } from 'dotenv';
import { resolve } from 'node:path';
import { createDb, createPool } from './index';
import { businessEntities } from './schema';

config({ path: resolve(__dirname, '../../../../.env') });

const seedEntities = [
  { jobCodeEntity: "0014", segment1: "1034", legalEntityName: "McDermott Investments, LLC", ledgerName: "US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0029", segment1: "1069", legalEntityName: "McDermott Subsea Engineering, Inc.", ledgerName: "US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0037", segment1: "1068", legalEntityName: "McDermott Caspian Contractors, Inc. - Azerbaijan", ledgerName: "KZ_KZT_PL", inventoryOrgName: "KZ JMO 1068 ORG", inventoryOrgCode: "KZ_JMO_1068_ORG" },
  { jobCodeEntity: "0053", segment1: "1086", legalEntityName: "SparTEC, Inc.", ledgerName: "US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0084", segment1: "1113", legalEntityName: "J. Ray McDermott (Nigeria) Ltd.", ledgerName: "NI_NGR_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0088", segment1: "1043", legalEntityName: "PT. J. Ray McDermott Indonesia", ledgerName: "JV_PTJRay_ID_IDR_PL", inventoryOrgName: "ID BFY 1043 ORG", inventoryOrgCode: "ID_BFY_1043_ORG" },
  { jobCodeEntity: "0111", segment1: "1049", legalEntityName: "McDermott Subsea, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0139", segment1: "1048", legalEntityName: "McDermott Old JV Office, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0160", segment1: "1001", legalEntityName: "McDermott Intl Inc", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0168", segment1: "1012", legalEntityName: "McDermott Gulf Operating Company, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0169", segment1: "1017", legalEntityName: "McDermott Asia Pacific Pte Ltd", ledgerName: "SG_SGD_PL", inventoryOrgName: "SG SGP 1017 ORG", inventoryOrgCode: "SG_SGP_1017_ORG" },
  { jobCodeEntity: "0172", segment1: "1014", legalEntityName: "Hydro Marine Services, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: "PA APM 1014 ORG", inventoryOrgCode: "PA_APM_1014_ORG" },
  { jobCodeEntity: "0173", segment1: "1014", legalEntityName: "Hydro Marine Services, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: "PA APM 1014 ORG", inventoryOrgCode: "PA_APM_1014_ORG" },
  { jobCodeEntity: "0203", segment1: "1013", legalEntityName: "North Atlantic Vessel, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0209", segment1: "1084", legalEntityName: "McDermott Servicos Offshore do Brasil Ltda.", ledgerName: "BR_BRL_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0210", segment1: "1016", legalEntityName: "McDermott Far East Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0213", segment1: "1046", legalEntityName: "P. T. McDermott Indonesia", ledgerName: "JV_PTBatam_ID_IDR_PL", inventoryOrgName: "ID BFY 1046 ORG", inventoryOrgCode: "ID_BFY_1046_ORG" },
  { jobCodeEntity: "0216", segment1: "1120", legalEntityName: "McDermott International Marine Investments N.V.", ledgerName: "NL_EUR_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0242", segment1: "1104", legalEntityName: "McDermott International B.V.", ledgerName: "NL_EUR_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0243", segment1: "1037", legalEntityName: "J. Ray McDermott (Aust.) Holding Pty. Limited", ledgerName: "AU_AUD_PL1", inventoryOrgName: "AU PER 1037 ORG", inventoryOrgCode: "AU_PER_1037_ORG" },
  { jobCodeEntity: "0244", segment1: "1075", legalEntityName: "McDermott Australia Pty. Ltd.", ledgerName: "AU_AUD_PL", inventoryOrgName: "AU PER 1075 ORG", inventoryOrgCode: "AU_PER_1075_ORG" },
  { jobCodeEntity: "0258", segment1: "1001", legalEntityName: "McDermott International, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0264", segment1: "1038", legalEntityName: "EMS - Atlantic Branch", ledgerName: "PA_USD_PL", inventoryOrgName: "PA APM 1038 ORG", inventoryOrgCode: "PA_APM_1038_ORG" },
  { jobCodeEntity: "0269", segment1: "1014", legalEntityName: "Hydro Marine Services, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: "PA APM 1014 ORG", inventoryOrgCode: "PA_APM_1014_ORG" },
  { jobCodeEntity: "0280", segment1: "1106", legalEntityName: "Delta Catalytic (Holland) B.V.", ledgerName: "NL_EUR_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0281", segment1: "1109", legalEntityName: "J. Ray McDermott Investments B.V.", ledgerName: "NL_EUR_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0283", segment1: "1100", legalEntityName: "McDermott Overseas Investment Co. N.V.", ledgerName: "NL_EUR_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0294", segment1: "1025", legalEntityName: "McDermott Offshore Services Company, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0295", segment1: "1047", legalEntityName: "McDermott Middle East, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0341", segment1: "1050", legalEntityName: "J. Ray McDermott Far East, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: "PA KUL 1050 ORG", inventoryOrgCode: "PA_KUL_1050_ORG" },
  { jobCodeEntity: "0342", segment1: "1050", legalEntityName: "J. Ray McDermott Far East, Inc. (Accounting)", ledgerName: null, inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0349", segment1: "1022", legalEntityName: "McDermott Overseas, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0393", segment1: "1028", legalEntityName: "Malmac Sdn. Bhd.", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KUL 1028 ORG", inventoryOrgCode: "MY_KUL_1028_ORG" },
  { jobCodeEntity: "0432", segment1: "1011", legalEntityName: "Chartering Company (Singapore) Pte. Ltd.", ledgerName: "SG_SGD_PL", inventoryOrgName: "SG SGP 1011 ORG", inventoryOrgCode: "SG_SGP_1011_ORG" },
  { jobCodeEntity: "0452", segment1: "1015", legalEntityName: "McDermott Holdings (U.K.) Limited", ledgerName: "UK_GBP_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0453", segment1: "1099", legalEntityName: "McDermott Azerbaijan Marine Construction, Inc.", ledgerName: "JV_AMC_PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0454", segment1: "1039", legalEntityName: "J Ray McD Far East - Brunei Branch", ledgerName: "BN_BND_PL", inventoryOrgName: "BN BRN 1039 ORG", inventoryOrgCode: "BN_BRN_1039_ORG" },
  { jobCodeEntity: "0466", segment1: "1050", legalEntityName: "J. Ray McDermott Far East, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: "PA KUL 1050 ORG", inventoryOrgCode: "PA_KUL_1050_ORG" },
  { jobCodeEntity: "0473", segment1: "1004", legalEntityName: "McDermott International Investments Co., Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0476", segment1: "1009", legalEntityName: "McDermott International Trading Co., Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0477", segment1: "1014", legalEntityName: "Hydro Marine Services, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: "PA APM 1014 ORG", inventoryOrgCode: "PA_APM_1014_ORG" },
  { jobCodeEntity: "0480", segment1: "1038", legalEntityName: "Eastern Marine Services, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: "PA_APM_1038_ORG" },
  { jobCodeEntity: "0481", segment1: "1103", legalEntityName: "Varsy International N.V.", ledgerName: "NL_EUR_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0619", segment1: "1042", legalEntityName: "PT. Baja Wahana Indonesia", ledgerName: "ID_IDR_PL", inventoryOrgName: "ID BFY 1042 ORG", inventoryOrgCode: "ID_BFY_1042_ORG" },
  { jobCodeEntity: "0839", segment1: "1018", legalEntityName: "JRMSA SEA Br Consol POC Div", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0848", segment1: "1020", legalEntityName: "McDermott Caspian Contractors, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: "PA BKU 1020 ORG", inventoryOrgCode: "PA_BKU_1020_ORG" },
  { jobCodeEntity: "0894", segment1: "1036", legalEntityName: "McDermott Marine Construction Limited", ledgerName: "UK_GBP_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0898", segment1: "1132", legalEntityName: "McDermott Eastern Hemisphere, Ltd. - Qatar Branch", ledgerName: "QA_QAR_PL", inventoryOrgName: "QA DOH 1064 ORG", inventoryOrgCode: "QA_DOH_1132_ORG" },
  { jobCodeEntity: "0898*", segment1: "1078", legalEntityName: "McDermott Eastern Hemisphere, Ltd.", ledgerName: null, inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0921", segment1: "1027", legalEntityName: "McDermott Arabia Company Limited", ledgerName: null, inventoryOrgName: "SA ALK 1027 ORG", inventoryOrgCode: "SA_ALK_1027_ORG" },
  { jobCodeEntity: "0923", segment1: "1063", legalEntityName: "McDermott Middle East, Inc. - Jebel Ali (UAE)", ledgerName: "AE_AED_PL", inventoryOrgName: "AE JFY 1063 ORG", inventoryOrgCode: "AE_JFY_1063_ORG" },
  { jobCodeEntity: "0950", segment1: "1064", legalEntityName: "McDermott Middle East, Inc. - Qatar Branch", ledgerName: "QA_QAR_PL", inventoryOrgName: "QA DOH 1064 ORG", inventoryOrgCode: "QA_DOH_1064_ORG" },
  { jobCodeEntity: "0998", segment1: "1094", legalEntityName: "Spars International Inc.", ledgerName: "JV_SPARS_US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "0999", segment1: "1097", legalEntityName: "Deep Oil Technology, Inc.", ledgerName: "US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1001", segment1: "1070", legalEntityName: "McDermott, Inc.", ledgerName: "US_USD_PL", inventoryOrgName: "US LDN 1070 ORG", inventoryOrgCode: "US_LDN_1070_ORG" },
  { jobCodeEntity: "1002", segment1: "1070", legalEntityName: "JRMI Marine Division", ledgerName: "US_USD_PL", inventoryOrgName: "US LDN 1070 ORG", inventoryOrgCode: "US_LDN_1070_ORG" },
  { jobCodeEntity: "1008", segment1: "1070", legalEntityName: "JRMI Fabricators Division", ledgerName: "US_USD_PL", inventoryOrgName: "US LDN 1070 ORG", inventoryOrgCode: "US_LDN_1070_ORG" },
  { jobCodeEntity: "1012", segment1: "1072", legalEntityName: "OPI Vessels, Inc.", ledgerName: "US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1013", segment1: "1088", legalEntityName: "J. Ray McDermott International Vessels, Ltd.", ledgerName: "KY_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1014", segment1: "1035", legalEntityName: "J. Ray McDermott Holdings, LLC", ledgerName: "US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1015", segment1: "1071", legalEntityName: "J. Ray McDermott Technology, Inc.", ledgerName: "US_USD_PL", inventoryOrgName: "x", inventoryOrgCode: null },
  { jobCodeEntity: "1030", segment1: "1023", legalEntityName: "J. Ray McDermott International, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1183", segment1: "1183", legalEntityName: "McDermott International Management, S. de RL. - India Branch", ledgerName: "IN_INR_PL", inventoryOrgName: "IN  CNN 1183 ORG", inventoryOrgCode: "IN_CNN_1183_ORG" },
  { jobCodeEntity: "1184", segment1: "1184", legalEntityName: "J. Ray McDermott, S.A. - Taiwan Branch", ledgerName: "TW_TWD_PL", inventoryOrgName: "TW KUL 1184 ORG", inventoryOrgCode: "TW_KUL_1184_ORG" },
  { jobCodeEntity: "1186", segment1: "1186", legalEntityName: "McDermott Trinidad, Ltd.", ledgerName: null, inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1232", segment1: "1112", legalEntityName: "WD 140 Platform LLC", ledgerName: "JV_WD_US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1240", segment1: "1005", legalEntityName: "McDermott Cayman Ltd.", ledgerName: "KY_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1241", segment1: "1010", legalEntityName: "Boudin Insurance Company, Ltd.", ledgerName: "BM_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1258", segment1: "1007", legalEntityName: "J. Ray McDermott, S.A.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1369", segment1: "1080", legalEntityName: "J. Ray McDermott de Mexico, S.A. de C.V.", ledgerName: "MX_MXN_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1370", segment1: "1065", legalEntityName: "McDermott Middle East Inc. - Abu Dhabi br. (UAE)", ledgerName: "AE_AED_PL", inventoryOrgName: "AE JMO 1065 ORG", inventoryOrgCode: "AE_JMO_1065_ORG" },
  { jobCodeEntity: "1372", segment1: "1024", legalEntityName: "International Vessels Ltd.", ledgerName: "MU_MUR_PL", inventoryOrgName: "MU KUL 1024 ORG", inventoryOrgCode: "MU_KUL_1024_ORG" },
  { jobCodeEntity: "1373", segment1: "1021", legalEntityName: "Deepwater Marine Technology, L.L.C.", ledgerName: "JV_DMT_KY_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1415", segment1: "1075", legalEntityName: "McDermott Australia Pty. Ltd.", ledgerName: "AU_AUD_PL", inventoryOrgName: "AU PEH 1075 ORG", inventoryOrgCode: "AU_PEH_1075_ORG" },
  { jobCodeEntity: "1416", segment1: "1063", legalEntityName: "McDermott Middle East, Inc. - Jebel Ali (UAE)", ledgerName: "AE_AED_PL", inventoryOrgName: "AE JON 1063 ORG", inventoryOrgCode: "AE _JON_1063_ORG" },
  { jobCodeEntity: "1417", segment1: "1046", legalEntityName: "P. T. McDermott Indonesia", ledgerName: "JV_PTBatam_ID_IDR_PL", inventoryOrgName: "ID BUO 1046 ORG", inventoryOrgCode: "ID_BUO_1046_ORG" },
  { jobCodeEntity: "1418", segment1: "1080", legalEntityName: "J. Ray McDermott de Mexico, S.A. de C.V.", ledgerName: "MX_MXN_PL", inventoryOrgName: "MX EAA 1080 ORG", inventoryOrgCode: "MX_EAA_1080_ORG" },
  { jobCodeEntity: "1419", segment1: "1046", legalEntityName: "P. T. McDermott Indonesia", ledgerName: "JV_PTBatam_ID_IDR_PL", inventoryOrgName: "ID BAC 1046 ORG", inventoryOrgCode: "ID_BAC_1046_ORG" },
  { jobCodeEntity: "1420", segment1: "1040", legalEntityName: "J. Ray McDermott Engineering Services Pvt Ltd", ledgerName: "IN_INR_PL", inventoryOrgName: "IN CAC 1040 ORG", inventoryOrgCode: "IN _CAC_1040_ORG" },
  { jobCodeEntity: "1421", segment1: "1014", legalEntityName: "Hydro Marine Services, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: "PA AUO 1014 ORG", inventoryOrgCode: "PA_AUO_1014_ORG" },
  { jobCodeEntity: "1422", segment1: "1031", legalEntityName: "McDermott Asia Pacific Sdn. Bhd.", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KUO 1031 ORG", inventoryOrgCode: "MY_KUO_1031_ORG" },
  { jobCodeEntity: "1423", segment1: "1063", legalEntityName: "McDermott Middle East, Inc. - Jebel Ali (UAE)", ledgerName: "AE_AED_PL", inventoryOrgName: "AE JSF 1063 ORG", inventoryOrgCode: "AE_JSF_1063_ORG" },
  { jobCodeEntity: "1424", segment1: "1050", legalEntityName: "J. Ray McDermott Far East, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: "PA KUO 1050 ORG", inventoryOrgCode: "PA_KUO_1050_ORG" },
  { jobCodeEntity: "1425", segment1: "1080", legalEntityName: "J. Ray McDermott de Mexico, S.A. de C.V.", ledgerName: "MX_MXN_PL", inventoryOrgName: "MX AAE 1080 ORG", inventoryOrgCode: "MX_AAE_1080_ORG" },
  { jobCodeEntity: "1426", segment1: "1075", legalEntityName: "McDermott Australia Pty. Ltd.", ledgerName: "AU_AUD_PL", inventoryOrgName: "AU PUO 1075 ORG", inventoryOrgCode: "AU_PUO_1075_ORG" },
  { jobCodeEntity: "1427", segment1: "1040", legalEntityName: "J. Ray McDermott Engineering Services Pvt Ltd", ledgerName: "IN_INR_PL", inventoryOrgName: "IN COU 1040 ORG", inventoryOrgCode: "IN_COU_1040_ORG" },
  { jobCodeEntity: "1429", segment1: "1031", legalEntityName: "McDermott Asia Pacific Sdn. Bhd.", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KEH 1031 ORG", inventoryOrgCode: "MY_KEH_1031_ORG" },
  { jobCodeEntity: "1431", segment1: "1065", legalEntityName: "McDermott Middle East Inc. - Abu Dhabi br (UAE)", ledgerName: "AE_AED_PL", inventoryOrgName: "AE JON 1065 ORG", inventoryOrgCode: "AE_JON_1065_ORG" },
  { jobCodeEntity: "1432", segment1: "1080", legalEntityName: "J. Ray McDermott de Mexico, S.A. de C.V.", ledgerName: "MX_MXN_PL", inventoryOrgName: "MX AWH 1080 ORG", inventoryOrgCode: "MX_AWH_1080_ORG" },
  { jobCodeEntity: "1433", segment1: "1046", legalEntityName: "P. T. McDermott Indonesia", ledgerName: "JV_PTBatam_ID_IDR_PL", inventoryOrgName: "ID BEH 1046 ORG", inventoryOrgCode: "ID_BEH_1046_ORG" },
  { jobCodeEntity: "1434", segment1: "1040", legalEntityName: "J. Ray McDermott Engineering Services Pvt Ltd", ledgerName: "IN_INR_PL", inventoryOrgName: "IN CEH 1040 ORG", inventoryOrgCode: "IN_CEH_1040_ORG" },
  { jobCodeEntity: "1477", segment1: "1067", legalEntityName: "McDermott Caspian Contractors, Inc. - Azerbaijan", ledgerName: "AZ_AZN_PL", inventoryOrgName: "AZ BKU 1067 ORG", inventoryOrgCode: "AZ_BKU_1067_ORG" },
  { jobCodeEntity: "1489", segment1: "1489", legalEntityName: "MCDERMOTT ANGOLA LDA", ledgerName: null, inventoryOrgName: "AO LAD 1489 ORG", inventoryOrgCode: "AO_LAD_1489_ORG" },
  { jobCodeEntity: "1902", segment1: "1093", legalEntityName: "McDermott Engineering LLC", ledgerName: "USD", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1904", segment1: "1085", legalEntityName: "J. Ray McDermott Solutions Inc.", ledgerName: "USD", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "1971", segment1: "1060", legalEntityName: "Berlian McDermott (L) Limited", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KUL 1060 ORG", inventoryOrgCode: "MY_KUL_1060_ORG" },
  { jobCodeEntity: "2001", segment1: "1070", legalEntityName: "McDermott Inc - EARC", ledgerName: "US_USD_PL", inventoryOrgName: "US LDN 1070 ORG", inventoryOrgCode: "US_LDN_1070_ORG" },
  { jobCodeEntity: "2002", segment1: "1070", legalEntityName: "Centralized NCSA McDermott Inc.", ledgerName: "US_USD_PL", inventoryOrgName: "US LDN 1070 ORG", inventoryOrgCode: "US_LDN_1070_ORG" },
  { jobCodeEntity: "2089", segment1: "1111", legalEntityName: "Offshore Pipelines International, Ltd.", ledgerName: "JV_DMT_KY_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2097", segment1: "1030", legalEntityName: "Berlian McDermott Sdn. Bhd.", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KUL 1030 ORG", inventoryOrgCode: "MY_KUL_1030_ORG" },
  { jobCodeEntity: "2099", segment1: "1116", legalEntityName: "Offshore Pipelines Nigeria Limited", ledgerName: "JV_OPN_NI_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2100", segment1: "1092", legalEntityName: "FloaTEC, LLC", ledgerName: "JV_FloaTEC_US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2101", segment1: "1040", legalEntityName: "J. Ray McDermott Engineering Services Private Limited", ledgerName: "IN_INR_PL", inventoryOrgName: "IN CNE 1040 ORG", inventoryOrgCode: "IN_CNE_1040_ORG" },
  { jobCodeEntity: "2103", segment1: "1119", legalEntityName: "J. Ray McDermott Kazakhstan LLP", ledgerName: "KZ_KZT_PL", inventoryOrgName: "KZ JMO 1119 ORG", inventoryOrgCode: "KZ_JMO_1119_ORG" },
  { jobCodeEntity: "2104", segment1: "1067", legalEntityName: "McDermott Caspian Contractors, Inc. - Azerbaijan", ledgerName: "AZ_AZN_PL", inventoryOrgName: "AZ BKU 1067 ORG", inventoryOrgCode: "AZ_BKU_1067_ORG" },
  { jobCodeEntity: "2106", segment1: "1051", legalEntityName: "J. Ray McDermott Underwater Services, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2118", segment1: "1102", legalEntityName: "J. Ray McDermott Canada, Ltd.", ledgerName: "CN_CAD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2120", segment1: "1019", legalEntityName: "McDermott International Vessels, Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2121", segment1: "1098", legalEntityName: "J. Ray McDermott Canada Holding, Ltd.", ledgerName: "CN_CAD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2124", segment1: "1044", legalEntityName: "J. Ray McDermott Logistic Services Pvt. Limited", ledgerName: "IN_INR_PL", inventoryOrgName: "IN MBI 1044 ORG", inventoryOrgCode: "IN_MBI_1044_ORG" },
  { jobCodeEntity: "2125", segment1: "1082", legalEntityName: "Servicios Profesionales de Altamira, S.A. de C.V.", ledgerName: "MX_MXN_PL1", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2126", segment1: "1081", legalEntityName: "Servicios de Fabricacion de Altamira, S.A. de C.V.", ledgerName: "MX_MXN_PL1", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2135", segment1: "1041", legalEntityName: "J.Ray McDermott(Qingdao) Pte Ltd", ledgerName: "SG_SGD_PL", inventoryOrgName: "SG SGP 1041 ORG", inventoryOrgCode: "SG_SGP_1041_ORG" },
  { jobCodeEntity: "2136", segment1: "1053", legalEntityName: "McDermott Marine Mexico, S.A. de C.V.", ledgerName: "MX_MXN_PL1", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2137", segment1: "1077", legalEntityName: "Qingdao McDermott Wuchuan Offshore Engineering Co., Ltd.", ledgerName: "JV_QMW_CN_CNY_PL", inventoryOrgName: "CN QMW 1077 ORG", inventoryOrgCode: "CN_QMW_1077_ORG" },
  { jobCodeEntity: "2173", segment1: "1076", legalEntityName: "Singapore Huangdao Pte Ltd", ledgerName: "SG_SGD_PL", inventoryOrgName: "SG SGP 1076 ORG", inventoryOrgCode: "SG_SGP_1076_ORG" },
  { jobCodeEntity: "2174", segment1: "1054", legalEntityName: "FloaTEC Singapore Pte. Ltd.", ledgerName: "JV_FloaTEC_SG_USD_PL", inventoryOrgName: "SG FLT 1054 ORG", inventoryOrgCode: "SG_FLT_1054_ORG" },
  { jobCodeEntity: "2180", segment1: "1052", legalEntityName: "J. Ray McDermott (Norway) AS", ledgerName: "NOK", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2181", segment1: "1026", legalEntityName: "McDermott Arabia Holdings Inc.", ledgerName: "USD", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2184", segment1: "1019", legalEntityName: "MIVI Asia Pacific Division", ledgerName: "PA_USD_PL", inventoryOrgName: "PA APM 1014 ORG", inventoryOrgCode: "PA_APM_1014_ORG" },
  { jobCodeEntity: "2191", segment1: "1055", legalEntityName: "FloaTEC de Mexico, S.A. de C.V.", ledgerName: "JV_FloaTEC_MX_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2193", segment1: "1083", legalEntityName: "North Ocean 105 AS", ledgerName: "NO_NOK_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2194", segment1: "1006", legalEntityName: "J. Ray McDermott (Luxembourg) S.ar.l.", ledgerName: "LU_EUR_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2195", segment1: "1012", legalEntityName: "MGOC - GMO Division", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2199", segment1: "1008", legalEntityName: "J. Ray Holdings, Inc.", ledgerName: "US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2206", segment1: "1117", legalEntityName: "McDermott Engineering L.L.C and Khalid Suhail Al Shoaibi for Engineering Consultancy", ledgerName: "JV_MKS_SA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2208", segment1: "1056", legalEntityName: "FloaTEC Offshore Servicos de Petroleo do Brasil Ltda.", ledgerName: "JV_FloaTEC_BR_BRL_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2213", segment1: "1045", legalEntityName: "ELDRIDGE PTE LTD", ledgerName: "SG_SGD_PL", inventoryOrgName: "SG SGP 1045 ORG", inventoryOrgCode: "SG_SGP_1045_ORG" },
  { jobCodeEntity: "2214", segment1: "1084", legalEntityName: "McDermott Servicos Offshore do Brazil Operations", ledgerName: "BR_BRL_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2215", segment1: "1057", legalEntityName: "McDermott Holdings (M) Sdn Bhd", ledgerName: "MY_MYR_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2216", segment1: "1002", legalEntityName: "McDermott International Management, S. de RL.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2217", segment1: "1066", legalEntityName: "MACL Industrial Branch", ledgerName: "SA_SAR_PL", inventoryOrgName: "SA_DFY_1066_ORG", inventoryOrgCode: "SA_DFY_1066_ORG" },
  { jobCodeEntity: "2218", segment1: "1029", legalEntityName: "McDermott Capital Malaysia Sdn. Bhd.", ledgerName: "MY_MYR_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2221", segment1: "1101", legalEntityName: "Deepsea Group Limited", ledgerName: "AE_AED_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2222", segment1: "1105", legalEntityName: "DeepSea (Americas) LLC", ledgerName: "US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2223", segment1: "1107", legalEntityName: "DeepSea Europe Limited", ledgerName: "UK_GBP_PL1", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2224", segment1: "1108", legalEntityName: "Deepsea (Asia Pacific) Limited", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KUL 1108 ORG", inventoryOrgCode: "MY_KUL_1108_ORG" },
  { jobCodeEntity: "2225", segment1: "1110", legalEntityName: "Deepsea (US) Incorporated", ledgerName: "US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2226", segment1: "1114", legalEntityName: "Deepsea (UK) Limited", ledgerName: "UK_GBP_PL1", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2227", segment1: "1114", legalEntityName: "DeepSea Holland Limited", ledgerName: "UK_GBP_PL1", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2228", segment1: "1115", legalEntityName: "DeepSea Engineering (Thailand) Limited", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KUL 1115 ORG", inventoryOrgCode: "MY_KUL_1115_ORG" },
  { jobCodeEntity: "2229", segment1: "1115", legalEntityName: "DeepSea Engineering Malaysia Sdn Bh", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KUL 1115 ORG", inventoryOrgCode: "MY_KUL_1115_ORG" },
  { jobCodeEntity: "2230", segment1: "1036", legalEntityName: "MMCL (Subsea)", ledgerName: "UK_GBP_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2231", segment1: "1070", legalEntityName: "McDermott Subsea", ledgerName: "US_USD_PL", inventoryOrgName: "US LDN 1070 ORG", inventoryOrgCode: "US_LDN_1070_ORG" },
  { jobCodeEntity: "2232", segment1: "1118", legalEntityName: "THHE McDermott Project Services Sdn. Bhd.", ledgerName: "JV_TMP_MY_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2233", segment1: "1061", legalEntityName: "THHE McDermott Engineering Sdn Bhd", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KUL 1061 ORG", inventoryOrgCode: "MY_KUL_1061_ORG" },
  { jobCodeEntity: "2235", segment1: "1030", legalEntityName: "Berlian McDermott Sdn Bhd-offshore", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KUL 1030 ORG", inventoryOrgCode: "MY_KUL_1030_ORG" },
  { jobCodeEntity: "2236", segment1: "1017", legalEntityName: "McDermott Asia Pacific Pte Ltd - Subsea", ledgerName: "SG_SGD_PL", inventoryOrgName: "SG SGP 1017 ORG", inventoryOrgCode: "SG_SGP_1017_ORG" },
  { jobCodeEntity: "2245", segment1: "1003", legalEntityName: "McDermott Finance L.L.C.", ledgerName: "US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2246", segment1: "1070", legalEntityName: "Global Subsea Offshore Operations", ledgerName: "US_USD_PL", inventoryOrgName: "US LDN 1070 ORG", inventoryOrgCode: "US_LDN_1070_ORG" },
  { jobCodeEntity: "2248", segment1: "1095", legalEntityName: "MCDERMOTT SUBSEA INC", ledgerName: "UK_GBP_PL1", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2250", segment1: "1044", legalEntityName: "JRMLS(India Liaison office)-SEA Div", ledgerName: "IN_INR_PL", inventoryOrgName: "IN MBI 1044 ORG", inventoryOrgCode: "IN_MBI_1044_ORG" },
  { jobCodeEntity: "2251", segment1: "1079", legalEntityName: "McDermott Marine Construction Ghana Limited", ledgerName: "GH_GHS_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2252", segment1: "1087", legalEntityName: "McDermott Blackbird Holdings, LLC", ledgerName: "US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2254", segment1: "1096", legalEntityName: "io Oil \u0026 Gas US, LLC", ledgerName: "JV_IO_US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2255", segment1: "1073", legalEntityName: "io Oil \u0026 Gas Management, LLC", ledgerName: "JV_IO_US_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2256", segment1: "1074", legalEntityName: "io Oil \u0026 Gas UK LLP", ledgerName: "JV_IO_UK_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2257", segment1: "1084", legalEntityName: "Brazil Offshore Operations", ledgerName: "BR_BRL_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2258", segment1: "1031", legalEntityName: "McDermott Asia Pacific Sdn. Bhd.", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KUL 1031 ORG", inventoryOrgCode: "MY_KUL_1031_ORG" },
  { jobCodeEntity: "2259", segment1: "1032", legalEntityName: "McDermott Project Support FZE", ledgerName: "AE_AED_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2260", segment1: "1059", legalEntityName: "JRMSA India Branch", ledgerName: "IN_INR_PL", inventoryOrgName: "IN MBI 1059 ORG", inventoryOrgCode: "IN_MBI_1059_ORG" },
  { jobCodeEntity: "2261", segment1: "1121", legalEntityName: "McDermott Marine Construction Limited - Equatorial Guinea Branch", ledgerName: "UK_GBP_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2262", segment1: "1090", legalEntityName: "McDermott CapeHydra Limited", ledgerName: "GH_GHS_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2263", segment1: "1018", legalEntityName: "McDermott (DLV 2000 Chartering), Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2264", segment1: "1089", legalEntityName: "McDermott Engineering Sdn Bhd", ledgerName: "MY_MYR_PL", inventoryOrgName: "MY KUL 1089 ORG", inventoryOrgCode: "MY_KUL_1089_ORG" },
  { jobCodeEntity: "2265", segment1: "1033", legalEntityName: "McDermott (Amazon Chartering), Inc.", ledgerName: "PA_USD_PL", inventoryOrgName: null, inventoryOrgCode: null },
  { jobCodeEntity: "2266", segment1: "1122", legalEntityName: "McDermott Arabia Company Limited - Jebel Ali Branch", ledgerName: "AE_AED_PL", inventoryOrgName: "AE JFY 1122 ORG", inventoryOrgCode: "AE_JFY_1122_ORG" },
  { jobCodeEntity: "MCD-EMEA", segment1: "ENGINEERING", legalEntityName: "McDermott Engineering EMEA BV", ledgerName: "McDermott EMEA Ledger", inventoryOrgName: "McDermott EMEA Engineering", inventoryOrgCode: "MCD-EMEA-ENG" },
  { jobCodeEntity: "MCD-UK", segment1: "CONSTRUCTION", legalEntityName: "McDermott Construction UK Ltd", ledgerName: "McDermott UK Ledger", inventoryOrgName: "McDermott UK Construction", inventoryOrgCode: "MCD-UK-CON" },
  { jobCodeEntity: "MCD-US", segment1: "ENERGY", legalEntityName: "McDermott Energy Services Inc", ledgerName: "McDermott US Ledger", inventoryOrgName: "McDermott US Energy", inventoryOrgCode: "MCD-US-ENG" },
] as const;

async function main() {
  const url = process.env.CREDITGUARD_DATABASE_URL;
  if (!url) throw new Error('CREDITGUARD_DATABASE_URL is not set');

  const pool = createPool(url);
  const db = createDb(pool);

  console.log('Seeding CreditGuard business entities...');
  for (const entity of seedEntities) {
    await db
      .insert(businessEntities)
      .values(entity)
      .onConflictDoUpdate({
        target: [businessEntities.jobCodeEntity, businessEntities.segment1, businessEntities.legalEntityName],
        set: {
          ledgerName: entity.ledgerName,
          inventoryOrgName: entity.inventoryOrgName,
          inventoryOrgCode: entity.inventoryOrgCode,
          updatedAt: new Date(),
        },
      });
  }

  await pool.end();
  console.log(`Seeded ${seedEntities.length} CreditGuard business entities.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
